version: "3.5"
services:
  call-center:
    image: 789252305933.dkr.ecr.cn-northwest-1.amazonaws.com.cn/tiktok-call-center:0.0.1
    environment:
      - PORT=3000
    ports:
      - 80:3000
    restart: always
    depends_on:
      - mongo
  
  mongo:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - ~/data/mongo:/data/db
    ports:
      - 27017:27017